<template>
  <div class="dashboard-grid">
    <section class="panel-box filter-panel"><div class="section-header-copy"><p class="section-kicker">玩家与运营</p><h2 class="section-title section-title--small">建议反馈管理</h2><p class="section-note">查看玩家建议、问题反馈和处理记录。</p></div><div class="filter-grid"><label class="field"><span>关键词</span><input v-model.trim="filters.keyword" placeholder="标题、内容、玩家" @keyup.enter="search" /></label><label class="field"><span>类型</span><select v-model="filters.type"><option value="">全部</option><option value="Suggestion">建议</option><option value="Bug">Bug</option><option value="Gameplay">玩法问题</option><option value="Account">账号问题</option><option value="Other">其他</option></select></label><label class="field"><span>状态</span><select v-model="filters.status"><option value="">全部</option><option value="Pending">待处理</option><option value="Processing">处理中</option><option value="Resolved">已解决</option><option value="Rejected">不予处理</option><option value="Closed">已关闭</option></select></label><div class="filter-actions"><button class="secondary-button" type="button" @click="search">查询</button></div></div></section>
    <section class="panel-box table-panel"><div class="section-header-row"><div class="section-header-copy"><p class="section-kicker">反馈列表</p><h3 class="section-title section-title--small">玩家反馈</h3></div><span class="selected-pill">共 {{ total }} 条</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>玩家</th><th>类型</th><th>标题</th><th>附件</th><th>状态</th><th>提交时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.id }}</td><td>{{ item.playerName }}<br><small>{{ item.playerId }}</small></td><td>{{ typeText[item.type] || item.type }}</td><td>{{ item.title }}</td><td>{{ item.attachmentCount }}</td><td><span class="status-badge" :class="statusClass(item.status)">{{ statusText[item.status] || item.status }}</span></td><td>{{ formatTime(item.createdAt) }}</td><td><button class="secondary-button secondary-button--sm" type="button" @click="open(item.id)">处理</button></td></tr><tr v-if="!items.length"><td colspan="8" class="empty-cell">暂无反馈记录</td></tr></tbody></table></div><div v-if="total > pageSize" class="pagination"><button class="secondary-button secondary-button--sm" type="button" :disabled="pageIndex <= 1" @click="changePage(pageIndex - 1)">上一页</button><span>第 {{ pageIndex }} / {{ totalPages() }} 页</span><button class="secondary-button secondary-button--sm" type="button" :disabled="pageIndex >= totalPages()" @click="changePage(pageIndex + 1)">下一页</button></div></section>
    <AdminModal v-model="modalOpen" kicker="反馈详情" :title="`反馈 #${detail?.id || ''}`" description="查看反馈原文、附件和状态历史，并填写处理结果。" size="wide"><div v-if="detail" class="detail-content"><div class="detail-summary"><div><span>玩家</span><strong>{{ detail.playerName }}</strong><small>{{ detail.playerId }}</small></div><div><span>类型</span><strong>{{ typeText[detail.type] || detail.type }}</strong></div><div><span>当前状态</span><span class="status-badge" :class="statusClass(detail.status)">{{ statusText[detail.status] || detail.status }}</span></div></div><h3 class="detail-title">{{ detail.title }}</h3><section class="detail-card"><div class="detail-card-title">反馈内容</div><p class="feedback-content">{{ detail.content }}</p></section><section v-if="detail.attachments.length" class="detail-card"><div class="detail-card-title">图片附件（{{ detail.attachments.length }}）</div><div class="images"><button v-for="image in detail.attachments" :key="image.id" type="button" class="image-button" @click="previewImage = buildAdminApiUrl(image.relativePath)"><img :src="buildAdminApiUrl(image.relativePath)" :alt="image.originalFileName || '反馈图片'" /></button></div></section><section v-if="detail.statusHistory.length" class="detail-card"><div class="detail-card-title">状态历史</div><div class="history-list"><div v-for="(history, index) in detail.statusHistory" :key="index" class="history-item"><span class="history-dot"></span><div><strong>{{ statusText[history.toStatus] || history.toStatus }}</strong><small>{{ history.fromStatus ? `${statusText[history.fromStatus] || history.fromStatus} → ` : '' }}{{ formatTime(history.createdAt) }} · 管理员 {{ history.adminId }}</small><p v-if="history.replySnapshot">回复：{{ history.replySnapshot }}</p></div></div></div></section><label class="field"><span>处理状态</span><select v-model="processForm.status"><option value="Processing">处理中</option><option value="Resolved">已解决</option><option value="Rejected">不予处理</option><option value="Closed">已关闭</option></select></label><label class="field"><span>玩家可见回复</span><textarea v-model="processForm.adminReply" rows="4" placeholder="填写玩家可以看到的处理结果"></textarea></label><label class="field"><span>内部备注</span><textarea v-model="processForm.internalNote" rows="3" placeholder="仅管理员可见"></textarea></label></div><template #footer><button class="secondary-button" type="button" @click="modalOpen = false">取消</button><button class="primary-button" type="button" :disabled="!canWritePlayers" @click="requestSave">保存处理结果</button></template></AdminModal>
    <AdminModal v-model="confirmOpen" kicker="确认处理" title="确认保存反馈处理结果" description="保存后会更新玩家可见状态，并写入状态历史。" size="wide"><div class="confirm-copy">确定将反馈 <strong>#{{ detail?.id }}</strong> 更新为 <strong>{{ statusText[processForm.status] || processForm.status }}</strong> 吗？</div><template #footer><button class="secondary-button" type="button" @click="confirmOpen = false">返回修改</button><button class="primary-button" type="button" @click="save">确认保存</button></template></AdminModal>
    <div v-if="previewImage" class="image-lightbox" @click.self="previewImage = ''"><button type="button" class="lightbox-close" @click="previewImage = ''">×</button><img :src="previewImage" alt="反馈图片大图" /></div>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import AdminModal from '@/components/AdminModal.vue'
import { buildAdminApiUrl } from '@/services/http'
import { useAdminPermissions } from '@/composables/useAdminPermissions'
import toast from '@/utils/toast'
import { getAdminFeedbackDetail, getAdminFeedbackList, processAdminFeedback } from '@/services/feedback'
import type { FeedbackDetail, FeedbackListItem, ProcessFeedbackPayload } from '@/types/admin'

const { canWritePlayers } = useAdminPermissions()
const items = ref<FeedbackListItem[]>([])
const total = ref(0)
const pageIndex = ref(1)
const pageSize = 20
const detail = ref<FeedbackDetail | null>(null)
const modalOpen = ref(false)
const confirmOpen = ref(false)
const previewImage = ref('')
const filters = reactive({ keyword: '', type: '', status: '' })
const processForm = reactive<ProcessFeedbackPayload>({ status: 'Processing', adminReply: '', internalNote: '' })
const statusText: Record<string, string> = { Pending: '待处理', Processing: '处理中', Resolved: '已解决', Rejected: '不予处理', Closed: '已关闭' }
const typeText: Record<string, string> = { Suggestion: '建议', Bug: 'Bug', Gameplay: '玩法问题', Account: '账号问题', Other: '其他' }

async function load() { try { const result = await getAdminFeedbackList(filters.keyword, filters.type, filters.status, pageIndex.value, pageSize); items.value = result.items; total.value = result.total } catch (error) { toast.error(error instanceof Error ? error.message : '反馈列表加载失败。') } }
function search() { pageIndex.value = 1; load() }
function totalPages() { return Math.max(1, Math.ceil(total.value / pageSize)) }
function changePage(nextPage: number) { pageIndex.value = Math.min(Math.max(1, nextPage), totalPages()); load() }
async function open(id: number) { try { detail.value = await getAdminFeedbackDetail(id); processForm.status = detail.value.status === 'Pending' ? 'Processing' : detail.value.status; processForm.adminReply = detail.value.adminReply || ''; processForm.internalNote = detail.value.internalNote || ''; modalOpen.value = true } catch (error) { toast.error(error instanceof Error ? error.message : '反馈详情加载失败。') } }
function requestSave() { if (detail.value && canWritePlayers.value) confirmOpen.value = true }
async function save() { if (!detail.value) return; confirmOpen.value = false; try { detail.value = await processAdminFeedback(detail.value.id, processForm); toast.success('反馈处理成功'); await load() } catch (error) { toast.error(error instanceof Error ? error.message : '反馈处理失败。') } }
function formatTime(value: string) { return value ? new Date(value).toLocaleString() : '' }
function statusClass(status: string) { return `status-${String(status || '').toLowerCase()}` }
onMounted(load)
</script>
<style scoped>
.filter-grid{align-items:end}.table-panel{overflow:hidden}.pagination{display:flex;align-items:center;justify-content:center;gap:16px;margin-top:16px;color:var(--text-secondary)}.empty-cell{text-align:center;color:var(--text-secondary)}.status-badge{display:inline-flex;align-items:center;justify-content:center;min-width:58px;padding:3px 8px;border:1px solid currentColor;border-radius:999px;font-size:12px;font-weight:600;white-space:nowrap}.status-pending{color:var(--status-warning-text);background:var(--status-warning-bg)}.status-processing{color:var(--status-info-text);background:var(--status-info-bg)}.status-resolved{color:var(--status-success-text);background:var(--status-success-bg)}.status-rejected,.status-closed{color:var(--text-secondary);background:var(--bg-overlay-light)}.detail-content{display:flex;flex-direction:column;gap:12px}.detail-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.detail-summary>div{display:flex;flex-direction:column;gap:4px;padding:12px;border:1px solid var(--border-color);border-radius:8px;background:var(--bg-overlay-light)}.detail-summary span:first-child{font-size:12px;color:var(--text-secondary)}.detail-summary small{color:var(--text-secondary)}.detail-title{margin:4px 0}.detail-card{padding:14px;border:1px solid var(--border-color);border-radius:8px;background:var(--bg-overlay-light)}.detail-card-title{margin-bottom:8px;color:var(--text-secondary);font-size:13px;font-weight:600}.feedback-content{margin:0;white-space:pre-wrap;line-height:1.7}.images{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:10px}.image-button{padding:0;border:0;background:transparent;cursor:zoom-in}.image-button img{display:block;width:100%;height:100px;border:1px solid var(--border-color);border-radius:6px;object-fit:cover}.history-list{display:flex;flex-direction:column;gap:12px}.history-item{display:flex;gap:10px}.history-dot{width:8px;height:8px;margin-top:6px;border-radius:50%;background:var(--accent-text);flex:none}.history-item strong,.history-item small{display:block}.history-item small{margin-top:3px;color:var(--text-secondary)}.history-item p{margin:5px 0 0;color:var(--text-primary)}.confirm-copy{padding:8px 0;line-height:1.8;color:var(--text-primary)}.image-lightbox{position:fixed;inset:0;z-index:1200;display:flex;align-items:center;justify-content:center;padding:24px;background:var(--overlay-bg);cursor:zoom-out}.image-lightbox img{max-width:92vw;max-height:86vh;border:1px solid var(--border-color);border-radius:8px;object-fit:contain}.lightbox-close{position:absolute;top:16px;right:16px;width:34px;height:34px;border:1px solid var(--border-color);border-radius:50%;background:var(--control-bg);color:var(--control-text);cursor:pointer;font-size:24px;line-height:1}@media (max-width:640px){.detail-summary{grid-template-columns:1fr}.pagination{gap:8px}}
</style>
